# Generated by Django 3.2.5 on 2021-08-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date_and_time', models.DateField()),
                ('event_id', models.CharField(max_length=12)),
                ('event_duration', models.DurationField()),
                ('event_signed_by', models.CharField(max_length=200)),
                ('event_approved_by', models.CharField(max_length=200)),
                ('event_participants', models.CharField(max_length=250)),
            ],
        ),
    ]
