# Generated by Django 3.2.5 on 2021-08-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=25, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('Rwandeese', 'Rwandees'), ('South Sudaneese', 'South Sudaneese')], max_length=15, null=True)),
                ('national_id', models.CharField(blank=True, max_length=18, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('county', models.CharField(blank=True, max_length=12, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('date_hired', models.DateField(blank=True, max_length=8, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='')),
                ('language', models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili')], max_length=10, null=True)),
            ],
        ),
    ]
