# Generated by Django 3.2.3 on 2021-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_alter_trainers_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
