# Generated by Django 3.2.5 on 2021-08-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='county',
            new_name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='age',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_of_enrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='course',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='course',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='course',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_desription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_syllabus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_trainer',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_of_course',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_of_course',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
