# Generated by Django 3.2.3 on 2021-08-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210820_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_desription',
        ),
    ]
