# Generated by Django 3.2.3 on 2021-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
