# Generated by Django 3.2.3 on 2021-08-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='serial_number',
        ),
    ]
