# Generated by Django 3.2.3 on 2021-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(upload_to='media'),
        ),
    ]
